// Package data embeds the extracted game data so the binary carries it and
// does not depend on files being present at runtime.
//
// The contents are generated by the nushell pipeline in this directory; see
// the README here for how to regenerate them.
// Nothing here interprets them; see internal/pkg/game for that.
package data

import _ "embed"

// DiceJSON is data/dice.json: every die in the game with its face weights.
//
//go:embed dice.json
var DiceJSON []byte
